package com.eight87.tonearmboy.data.albumart

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import java.util.concurrent.TimeUnit

/**
 * Cover-art Phase B — YouTube cover-art provider.
 *
 * Video-ID resolution chain (first hit wins, all stages skipped on
 * null):
 *   1. Filename regex (`<title>-<11-char>.ext`, NewPipe default).
 *   2. **Round 4** — `COMMENT` / author-ish text tag via
 *      [TrackTagReader] + [YouTubeCommentExtractor]. Handles NewPipe
 *      downloads where the user renamed the file and the only surviving
 *      breadcrumb is the source URL baked into the COMMENT tag.
 *   3. Piped search by `artist + title`, optionally duration-filtered
 *      (Round 4 — caller passes `expectedDurationSec` for ±2 s match).
 *
 * After an ID is found, walk the thumbnail URL ladder
 * `maxres → sd → hq`; the lowest tier (`hqdefault.jpg`) always exists,
 * so the chain always returns a usable URL once we have an ID.
 *
 * The square-crop step lives in [AlbumArtFetcher] post-download
 * (Phase B.2) so MusicBrainz / iTunes covers benefit too.
 */
class YouTubeProvider(
  private val piped: PipedClient = PipedClient(),
  private val client: OkHttpClient = defaultClient(),
  private val baseUrl: String = "https://i.ytimg.com",
  /**
   * Optional tag reader for Round 4's COMMENT-tag stage. Null in tests
   * that only exercise the filename or Piped paths; non-null in
   * production wiring (see `ProviderRegistry.Deps.tagReader`).
   */
  private val tagReader: TrackTagReader? = null,
  /**
   * Round 5 — when true, HEAD-walks `maxresdefault → sddefault →
   * hqdefault` to surface the highest-res variant the uploader has.
   * Default false: skip the ladder, return `hqdefault.jpg` directly.
   * `hqdefault` is generated by YouTube for *every* upload, so it's
   * the rate-courteous default — two HEAD requests per track adds up
   * fast on a 2000-song library.
   */
  private val probeMaxRes: Boolean = false,
) : CoverArtProvider {
  override val kind: ProviderKind = ProviderKind.YouTube

  override suspend fun findCover(req: CoverArtRequest): ProviderResult? {
    val diags = mutableListOf<StageDiag>()

    // Stage 1 — filename.
    val path = req.sampleTrackPath
    val filenameId = path?.let { YouTubeIdExtractor.fromFilename(it) }
    diags += StageDiag.Filename(matched = filenameId)
    if (filenameId != null) {
      val url = pickBestThumbnail(filenameId)
      return ProviderResult(kind, url, ResolutionSource.Filename, filenameId, diags.toList())
    }

    // Stage 2 — tag (Round 4). Only attempted when a path AND a reader
    // are both present; reading tags off content URIs / a missing
    // reader records a Filename-only diag list and moves on.
    val reader = tagReader
    if (reader != null && path != null) {
      val scan = runCatching { reader.readTextTagsRich(path) }
        .getOrDefault(TagScanResult(null, 0, 0, 0))
      val tagId = YouTubeCommentExtractor.fromCommentText(scan.captured)
      diags += StageDiag.CommentTag(
        captured = scan.captured?.take(80),
        matched = tagId,
        bytesScanned = scan.bytesScanned,
      )
      if (tagId != null) {
        val url = pickBestThumbnail(tagId)
        return ProviderResult(kind, url, ResolutionSource.CommentTag, tagId, diags.toList())
      }
    }

    // Stage 3 — Piped search. May throw [ThrottledException] which
    // propagates to the chain (and disables this provider for the
    // rest of the bulk run). On throttle we still stash the diags so
    // the log row shows the filename + tag-scan history that ran
    // before Piped blew up.
    val pipedDiag = try {
      piped.searchRich(req.albumArtist, req.albumName, req.expectedDurationSec)
    } catch (t: ThrottledException) {
      lastMissDiags = diags.toList()
      throw t
    }
    diags += pipedDiag
    val pipedId = pipedDiag.matchedId
    if (pipedId != null) {
      val url = pickBestThumbnail(pipedId)
      return ProviderResult(kind, url, ResolutionSource.PipedSearch, pipedId, diags.toList())
    }

    // Miss — stash diags so the chain can surface them on the log
    // row for the no-match track. `lastMissDiags` is read once per
    // worker iteration on the single bulk-art thread, so no concurrency
    // hazard. See [AlbumArtBulkWorker] for the consumer.
    lastMissDiags = diags.toList()
    return null
  }

  /**
   * Round 6 / Fix C — last `findCover` invocation's collected
   * diagnostics when that call resolved to null (a miss). Cleared by
   * the worker between tracks. Single-thread bulk worker → no need
   * to thread this through the chain return type.
   */
  @Volatile
  var lastMissDiags: List<StageDiag> = emptyList()
    private set

  fun clearMissDiags() {
    lastMissDiags = emptyList()
  }

  /**
   * Default Round 5 behaviour: return `hqdefault.jpg` directly. It
   * always exists, costs zero extra HEAD requests, and trades a bit
   * of resolution for rate-courtesy with YouTube's CDN. When
   * [probeMaxRes] is true we walk `maxresdefault → sddefault →
   * hqdefault` like Round 4 did. `maxresdefault` only exists for
   * 720p+ uploads, `sddefault` for 480p+, `hqdefault` for every video.
   */
  private suspend fun pickBestThumbnail(videoId: String): String = withContext(Dispatchers.IO) {
    if (!probeMaxRes) return@withContext "$baseUrl/vi/$videoId/hqdefault.jpg"
    for (tier in listOf("maxresdefault", "sddefault")) {
      val url = "$baseUrl/vi/$videoId/$tier.jpg"
      if (head(url)) return@withContext url
    }
    "$baseUrl/vi/$videoId/hqdefault.jpg"
  }

  private fun head(url: String): Boolean = runCatching {
    val req = Request.Builder().url(url).head().build()
    client.newCall(req).execute().use { resp -> resp.isSuccessful }
  }.getOrDefault(false)

  companion object {
    private fun defaultClient(): OkHttpClient = OkHttpClient.Builder()
      .connectTimeout(5, TimeUnit.SECONDS)
      .readTimeout(10, TimeUnit.SECONDS)
      .followRedirects(true)
      .build()
  }
}
