package com.eight87.tonearmboy.data.albumart

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import java.util.concurrent.TimeUnit

/**
 * Cover-art Phase B — YouTube cover-art provider.
 *
 * Video-ID resolution chain (first hit wins, all stages skipped on
 * null):
 *   1. Filename regex (`<title>-<11-char>.ext`, NewPipe default).
 *   2. **Round 4** — `COMMENT` / author-ish text tag via
 *      [TrackTagReader] + [YouTubeCommentExtractor]. Handles NewPipe
 *      downloads where the user renamed the file and the only surviving
 *      breadcrumb is the source URL baked into the COMMENT tag.
 *   3. Piped search by `artist + title`, optionally duration-filtered
 *      (Round 4 — caller passes `expectedDurationSec` for ±2 s match).
 *
 * After an ID is found, walk the thumbnail URL ladder
 * `maxres → sd → hq`; the lowest tier (`hqdefault.jpg`) always exists,
 * so the chain always returns a usable URL once we have an ID.
 *
 * The square-crop step lives in [AlbumArtFetcher] post-download
 * (Phase B.2) so MusicBrainz / iTunes covers benefit too.
 */
class YouTubeProvider(
  private val piped: PipedClient = PipedClient(),
  private val client: OkHttpClient = defaultClient(),
  private val baseUrl: String = "https://i.ytimg.com",
  /**
   * Optional tag reader for Round 4's COMMENT-tag stage. Null in tests
   * that only exercise the filename or Piped paths; non-null in
   * production wiring (see `ProviderRegistry.Deps.tagReader`).
   */
  private val tagReader: TrackTagReader? = null,
  /**
   * Round 5 — when true, HEAD-walks `maxresdefault → sddefault →
   * hqdefault` to surface the highest-res variant the uploader has.
   * Default false: skip the ladder, return `hqdefault.jpg` directly.
   * `hqdefault` is generated by YouTube for *every* upload, so it's
   * the rate-courteous default — two HEAD requests per track adds up
   * fast on a 2000-song library.
   */
  private val probeMaxRes: Boolean = false,
) : CoverArtProvider {
  override val kind: ProviderKind = ProviderKind.YouTube

  override suspend fun findCover(req: CoverArtRequest): ProviderResult? {
    val resolution = resolveVideoIdWithSource(req) ?: return null
    val (videoId, source) = resolution
    val url = pickBestThumbnail(videoId)
    return ProviderResult(kind, url, source, videoId)
  }

  /**
   * Round 5 — returns both the resolved video id AND the stage that
   * produced it so the bulk-art log can name "filename" vs "COMMENT
   * tag" vs "Piped search". Returns null when every stage missed (or
   * when stage 3 throws [ThrottledException], which propagates so the
   * chain can disable Piped for the rest of the run).
   */
  private suspend fun resolveVideoIdWithSource(req: CoverArtRequest): Pair<String, ResolutionSource>? {
    // Stage 1 — filename.
    req.sampleTrackPath?.let { path ->
      YouTubeIdExtractor.fromFilename(path)?.let { return it to ResolutionSource.Filename }
    }
    // Stage 2 — tag (Round 4). Only attempted when a path AND a reader
    // are both present; reading tags off content URIs / a missing
    // reader is a no-op fallthrough.
    val reader = tagReader
    val path = req.sampleTrackPath
    if (reader != null && path != null) {
      val blob = runCatching { reader.readTextTags(path) }.getOrNull()
      YouTubeCommentExtractor.fromCommentText(blob)?.let { return it to ResolutionSource.CommentTag }
    }
    // Stage 3 — Piped search. May throw [ThrottledException] which
    // propagates to the chain (and disables this provider for the
    // rest of the bulk run).
    val pipedId = piped.searchVideoId(req.albumArtist, req.albumName, req.expectedDurationSec)
    return pipedId?.let { it to ResolutionSource.PipedSearch }
  }

  /**
   * Default Round 5 behaviour: return `hqdefault.jpg` directly. It
   * always exists, costs zero extra HEAD requests, and trades a bit
   * of resolution for rate-courtesy with YouTube's CDN. When
   * [probeMaxRes] is true we walk `maxresdefault → sddefault →
   * hqdefault` like Round 4 did. `maxresdefault` only exists for
   * 720p+ uploads, `sddefault` for 480p+, `hqdefault` for every video.
   */
  private suspend fun pickBestThumbnail(videoId: String): String = withContext(Dispatchers.IO) {
    if (!probeMaxRes) return@withContext "$baseUrl/vi/$videoId/hqdefault.jpg"
    for (tier in listOf("maxresdefault", "sddefault")) {
      val url = "$baseUrl/vi/$videoId/$tier.jpg"
      if (head(url)) return@withContext url
    }
    "$baseUrl/vi/$videoId/hqdefault.jpg"
  }

  private fun head(url: String): Boolean = runCatching {
    val req = Request.Builder().url(url).head().build()
    client.newCall(req).execute().use { resp -> resp.isSuccessful }
  }.getOrDefault(false)

  companion object {
    private fun defaultClient(): OkHttpClient = OkHttpClient.Builder()
      .connectTimeout(5, TimeUnit.SECONDS)
      .readTimeout(10, TimeUnit.SECONDS)
      .followRedirects(true)
      .build()
  }
}
